version: "3.7"

services:

  # appコンテナ
  app:
    container_name: ddd-api-with-laravel-app
    hostname: ddd-api-with-laravel-app
    build:
      dockerfile: ./build/app/Dockerfile
      target: develop
      context: .
    image: ddd-api-with-laravel-app:latest
    tty: true
    expose:
      # nginxから転送されたリクエストを受信
      - "9000"
    volumes:
      # bindマウント
      - .:/var/www/ddd-api-with-laravel
    working_dir: /var/www/ddd-api-with-laravel
    networks:
      - default
    depends_on:
      - db

  # webコンテナ
  web:
    container_name: ddd-api-with-laravel-web
    hostname: ddd-api-with-laravel-web
    build:
      dockerfile: ./build/web/Dockerfile
      target: develop
      context: .
    image: ddd-api-with-laravel-web:latest
    ports:
      - "8000:80"
    volumes:
      # bindマウント
      - .:/var/www/ddd-api-with-laravel
    working_dir: /var/www/ddd-api-with-laravel
    networks:
      - default
    depends_on:
      - app

  # dbコンテナ
  db:
    container_name: ddd-api-with-laravel-db
    hostname: ddd-api-with-laravel-db
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      # volumeマウント
      - db_volume:/var/www/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - default

volumes:
  # volume名
  db_volume:
    # ホストOSのDockerエリアを指定
    driver: local
