version: "3.7"

services:

  # apiコンテナ
  api:
    container_name: tech-blog-api
    hostname: tech-blog-api
    build:
      dockerfile: ./infra/docker/api/Dockerfile
      target: develop
      context: .
    image: tech-blog-api:latest
    tty: true
    expose:
      # PHP-FPMからのリダイレクトを受信
      - "9000"
    volumes:
      # bindマウント
      - .:/var/www/tech-blog
    working_dir: /var/www/tech-blog
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    networks:
      - default
    depends_on:
      - db

  # webコンテナ
  web:
    container_name: tech-blog-web
    hostname: tech-blog-web
    build:
      dockerfile: ./infra/docker/www/Dockerfile
      target: develop
      context: .
    image: tech-blog-web:latest
    tty: true
    ports:
      - "8000:80"
    volumes:
      # bindマウント
      - .:/var/www/tech-blog
    working_dir: /var/www/tech-blog
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    networks:
      - default
    depends_on:
      - api

  # dbコンテナ
  db:
    container_name: tech-blog-db
    hostname: tech-blog-db
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      # volumeマウント
      - db_volume:/var/www/lib/mysql
    tty: true
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - default

volumes:
  # volume名
  db_volume:
    # ホストOSのDockerエリアを指定
    driver: local
