name: php-cs-fixer

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Setup git
        run: |
          git config --local user.email "hasegawafeedshop@gmail.com"
          git config --local user.name "github-actions"
      - name: Composer install
        run: |
          composer install --prefer-dist
      - name: Run php-cs-fixer
        run: |
          vendor/bin/php-cs-fixer fix .
      - name: Commit & Push
        run: |
          diff=`git diff | wc -l`
          if [ $diff -eq 0 ]; then
            echo "コミットされたファイルが見つからないため，GitHub Actionsを終了しました．"
            exit 0
          fi
          git add .
          git commit -m "GitHub Actions が PHP-CS-Fixer を実行しました．"
          git pull
          git push origin HEAD
